# 必須の設定
CLONE_URL: "git@github.com:langchain-ai/langchain.git" # クローンするリポジトリ
BRANCH: "master" # ブランチの指定

# オプションの設定
FILTER_EXT: "" # 単数または複数の拡張子をカンマ区切りで指定（半角スペースも許容）、空だとすべてのファイル．
DIR: "docs" # ディレクトリをカンマ区切りで指定、ルートを指定するには".""
LANG: "ja" # 言語設定（'ja' または 'en'）
